/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#bbc9cf",
        "outline-variant": "#3c494e",
        "inverse-primary": "#006875",
        "on-tertiary-container": "#414f63",
        "surface-container-lowest": "#0a0e14",
        "on-secondary-fixed": "#410001",
        "on-primary-container": "#005762",
        "inverse-on-surface": "#2d3137",
        "surface-container-high": "#262a31",
        "surface": "#10141a",
        "error-container": "#93000a",
        "surface-variant": "#31353c",
        "on-background": "#dfe2eb",
        "tertiary": "#cfddf6",
        "on-primary": "#00363d",
        "on-primary-fixed": "#001f24",
        "on-tertiary": "#233144",
        "secondary": "#ffb4aa",
        "secondary-fixed-dim": "#ffb4aa",
        "primary-fixed": "#9cf0ff",
        "on-tertiary-fixed": "#0e1c2e",
        "tertiary-fixed-dim": "#b9c7e0",
        "secondary-container": "#c5020b",
        "surface-container-highest": "#31353c",
        "surface-container-low": "#181c22",
        "error": "#ffb4ab",
        "on-primary-fixed-variant": "#004f58",
        "outline": "#859399",
        "tertiary-container": "#b3c1d9",
        "background": "#10141a",
        "on-surface": "#dfe2eb",
        "on-error": "#690005",
        "tertiary-fixed": "#d5e3fc",
        "surface-bright": "#353940",
        "primary-fixed-dim": "#00daf3",
        "on-secondary": "#690003",
        "on-error-container": "#ffdad6",
        "primary": "#7eecff",
        "inverse-surface": "#dfe2eb",
        "surface-container": "#1c2026",
        "secondary-fixed": "#ffdad5",
        "on-tertiary-fixed-variant": "#3a485b",
        "surface-dim": "#10141a",
        "primary-container": "#00d3ec",
        "surface-tint": "#00daf3",
        "on-secondary-fixed-variant": "#930005",
        "on-secondary-container": "#ffd2cc"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
